export interface CountryCode {
  code: string;
  flag: string;
  country: string;
  /** English display/search name. */
  name: string;
  /** Arabic display/search name. */
  nameAr: string;
}

/** Renders an ISO-2 country code as its flag emoji (e.g. "SA" → "🇸🇦"). */
function flagFor(country: string): string {
  return country
    .toUpperCase()
    .replace(/[A-Z]/g, (char) => String.fromCodePoint(127397 + char.charCodeAt(0)));
}

const E = flagFor;

/** Callable dialing codes offered in phone entry forms. */
export const COUNTRY_CODES: CountryCode[] = [
  // Gulf / primary market (kept on top for quick access).
  { code: "+966", flag: E("SA"), country: "SA", name: "Saudi Arabia", nameAr: "السعودية" },
  { code: "+965", flag: E("KW"), country: "KW", name: "Kuwait", nameAr: "الكويت" },
  { code: "+971", flag: E("AE"), country: "AE", name: "United Arab Emirates", nameAr: "الإمارات" },
  { code: "+974", flag: E("QA"), country: "QA", name: "Qatar", nameAr: "قطر" },
  { code: "+973", flag: E("BH"), country: "BH", name: "Bahrain", nameAr: "البحرين" },
  { code: "+968", flag: E("OM"), country: "OM", name: "Oman", nameAr: "عُمان" },
  { code: "+20", flag: E("EG"), country: "EG", name: "Egypt", nameAr: "مصر" },
  { code: "+1", flag: E("US"), country: "US", name: "United States", nameAr: "الولايات المتحدة" },

  // Zone 2 — Africa.
  { code: "+211", flag: E("SS"), country: "SS", name: "South Sudan", nameAr: "جنوب السودان" },
  { code: "+212", flag: E("MA"), country: "MA", name: "Morocco", nameAr: "المغرب" },
  { code: "+213", flag: E("DZ"), country: "DZ", name: "Algeria", nameAr: "الجزائر" },
  { code: "+216", flag: E("TN"), country: "TN", name: "Tunisia", nameAr: "تونس" },
  { code: "+218", flag: E("LY"), country: "LY", name: "Libya", nameAr: "ليبيا" },
  { code: "+220", flag: E("GM"), country: "GM", name: "Gambia", nameAr: "غامبيا" },
  { code: "+221", flag: E("SN"), country: "SN", name: "Senegal", nameAr: "السنغال" },
  { code: "+222", flag: E("MR"), country: "MR", name: "Mauritania", nameAr: "موريتانيا" },
  { code: "+223", flag: E("ML"), country: "ML", name: "Mali", nameAr: "مالي" },
  { code: "+224", flag: E("GN"), country: "GN", name: "Guinea", nameAr: "غينيا" },
  { code: "+225", flag: E("CI"), country: "CI", name: "Côte d'Ivoire", nameAr: "ساحل العاج" },
  { code: "+226", flag: E("BF"), country: "BF", name: "Burkina Faso", nameAr: "بوركينا فاسو" },
  { code: "+227", flag: E("NE"), country: "NE", name: "Niger", nameAr: "النيجر" },
  { code: "+228", flag: E("TG"), country: "TG", name: "Togo", nameAr: "توغو" },
  { code: "+229", flag: E("BJ"), country: "BJ", name: "Benin", nameAr: "بنين" },
  { code: "+230", flag: E("MU"), country: "MU", name: "Mauritius", nameAr: "موريشيوس" },
  { code: "+231", flag: E("LR"), country: "LR", name: "Liberia", nameAr: "ليبيريا" },
  { code: "+232", flag: E("SL"), country: "SL", name: "Sierra Leone", nameAr: "سيراليون" },
  { code: "+233", flag: E("GH"), country: "GH", name: "Ghana", nameAr: "غانا" },
  { code: "+234", flag: E("NG"), country: "NG", name: "Nigeria", nameAr: "نيجيريا" },
  { code: "+235", flag: E("TD"), country: "TD", name: "Chad", nameAr: "تشاد" },
  {
    code: "+236",
    flag: E("CF"),
    country: "CF",
    name: "Central African Republic",
    nameAr: "جمهورية أفريقيا الوسطى",
  },
  { code: "+237", flag: E("CM"), country: "CM", name: "Cameroon", nameAr: "الكاميرون" },
  { code: "+238", flag: E("CV"), country: "CV", name: "Cape Verde", nameAr: "الرأس الأخضر" },
  {
    code: "+239",
    flag: E("ST"),
    country: "ST",
    name: "São Tomé and Príncipe",
    nameAr: "ساو تومي وبرينسيبي",
  },
  {
    code: "+240",
    flag: E("GQ"),
    country: "GQ",
    name: "Equatorial Guinea",
    nameAr: "غينيا الاستوائية",
  },
  { code: "+241", flag: E("GA"), country: "GA", name: "Gabon", nameAr: "الغابون" },
  { code: "+242", flag: E("CG"), country: "CG", name: "Congo", nameAr: "الكونغو" },
  { code: "+243", flag: E("CD"), country: "CD", name: "DR Congo", nameAr: "الكونغو الديمقراطية" },
  { code: "+244", flag: E("AO"), country: "AO", name: "Angola", nameAr: "أنغولا" },
  { code: "+245", flag: E("GW"), country: "GW", name: "Guinea-Bissau", nameAr: "غينيا بيساو" },
  {
    code: "+246",
    flag: E("IO"),
    country: "IO",
    name: "British Indian Ocean Territory",
    nameAr: "إقليم المحيط الهندي البريطاني",
  },
  { code: "+248", flag: E("SC"), country: "SC", name: "Seychelles", nameAr: "سيشل" },
  { code: "+249", flag: E("SD"), country: "SD", name: "Sudan", nameAr: "السودان" },
  { code: "+250", flag: E("RW"), country: "RW", name: "Rwanda", nameAr: "رواندا" },
  { code: "+251", flag: E("ET"), country: "ET", name: "Ethiopia", nameAr: "إثيوبيا" },
  { code: "+252", flag: E("SO"), country: "SO", name: "Somalia", nameAr: "الصومال" },
  { code: "+253", flag: E("DJ"), country: "DJ", name: "Djibouti", nameAr: "جيبوتي" },
  { code: "+254", flag: E("KE"), country: "KE", name: "Kenya", nameAr: "كينيا" },
  { code: "+255", flag: E("TZ"), country: "TZ", name: "Tanzania", nameAr: "تنزانيا" },
  { code: "+256", flag: E("UG"), country: "UG", name: "Uganda", nameAr: "أوغندا" },
  { code: "+257", flag: E("BI"), country: "BI", name: "Burundi", nameAr: "بوروندي" },
  { code: "+258", flag: E("MZ"), country: "MZ", name: "Mozambique", nameAr: "موزمبيق" },
  { code: "+260", flag: E("ZM"), country: "ZM", name: "Zambia", nameAr: "زامبيا" },
  { code: "+261", flag: E("MG"), country: "MG", name: "Madagascar", nameAr: "مدغشقر" },
  { code: "+262", flag: E("RE"), country: "RE", name: "Réunion", nameAr: "ريونيون" },
  { code: "+263", flag: E("ZW"), country: "ZW", name: "Zimbabwe", nameAr: "زيمبابوي" },
  { code: "+264", flag: E("NA"), country: "NA", name: "Namibia", nameAr: "ناميبيا" },
  { code: "+265", flag: E("MW"), country: "MW", name: "Malawi", nameAr: "مالاوي" },
  { code: "+266", flag: E("LS"), country: "LS", name: "Lesotho", nameAr: "ليسوتو" },
  { code: "+267", flag: E("BW"), country: "BW", name: "Botswana", nameAr: "بوتسوانا" },
  { code: "+268", flag: E("SZ"), country: "SZ", name: "Eswatini", nameAr: "إسواتيني" },
  { code: "+269", flag: E("KM"), country: "KM", name: "Comoros", nameAr: "جزر القمر" },
  { code: "+27", flag: E("ZA"), country: "ZA", name: "South Africa", nameAr: "جنوب أفريقيا" },
  { code: "+290", flag: E("SH"), country: "SH", name: "Saint Helena", nameAr: "سانت هيلانة" },
  { code: "+291", flag: E("ER"), country: "ER", name: "Eritrea", nameAr: "إريتريا" },
  { code: "+297", flag: E("AW"), country: "AW", name: "Aruba", nameAr: "أروبا" },
  { code: "+298", flag: E("FO"), country: "FO", name: "Faroe Islands", nameAr: "جزر فارو" },
  { code: "+299", flag: E("GL"), country: "GL", name: "Greenland", nameAr: "جرينلاند" },

  // Zone 3 — Europe.
  { code: "+30", flag: E("GR"), country: "GR", name: "Greece", nameAr: "اليونان" },
  { code: "+31", flag: E("NL"), country: "NL", name: "Netherlands", nameAr: "هولندا" },
  { code: "+32", flag: E("BE"), country: "BE", name: "Belgium", nameAr: "بلجيكا" },
  { code: "+33", flag: E("FR"), country: "FR", name: "France", nameAr: "فرنسا" },
  { code: "+34", flag: E("ES"), country: "ES", name: "Spain", nameAr: "إسبانيا" },
  { code: "+350", flag: E("GI"), country: "GI", name: "Gibraltar", nameAr: "جبل طارق" },
  { code: "+351", flag: E("PT"), country: "PT", name: "Portugal", nameAr: "البرتغال" },
  { code: "+352", flag: E("LU"), country: "LU", name: "Luxembourg", nameAr: "لوكسمبورغ" },
  { code: "+353", flag: E("IE"), country: "IE", name: "Ireland", nameAr: "أيرلندا" },
  { code: "+354", flag: E("IS"), country: "IS", name: "Iceland", nameAr: "آيسلندا" },
  { code: "+355", flag: E("AL"), country: "AL", name: "Albania", nameAr: "ألبانيا" },
  { code: "+356", flag: E("MT"), country: "MT", name: "Malta", nameAr: "مالطا" },
  { code: "+357", flag: E("CY"), country: "CY", name: "Cyprus", nameAr: "قبرص" },
  { code: "+358", flag: E("FI"), country: "FI", name: "Finland", nameAr: "فنلندا" },
  { code: "+359", flag: E("BG"), country: "BG", name: "Bulgaria", nameAr: "بلغاريا" },
  { code: "+36", flag: E("HU"), country: "HU", name: "Hungary", nameAr: "المجر" },
  { code: "+370", flag: E("LT"), country: "LT", name: "Lithuania", nameAr: "ليتوانيا" },
  { code: "+371", flag: E("LV"), country: "LV", name: "Latvia", nameAr: "لاتفيا" },
  { code: "+372", flag: E("EE"), country: "EE", name: "Estonia", nameAr: "إستونيا" },
  { code: "+373", flag: E("MD"), country: "MD", name: "Moldova", nameAr: "مولدوفا" },
  { code: "+374", flag: E("AM"), country: "AM", name: "Armenia", nameAr: "أرمينيا" },
  { code: "+375", flag: E("BY"), country: "BY", name: "Belarus", nameAr: "بيلاروسيا" },
  { code: "+376", flag: E("AD"), country: "AD", name: "Andorra", nameAr: "أندورا" },
  { code: "+377", flag: E("MC"), country: "MC", name: "Monaco", nameAr: "موناكو" },
  { code: "+378", flag: E("SM"), country: "SM", name: "San Marino", nameAr: "سان مارينو" },
  { code: "+380", flag: E("UA"), country: "UA", name: "Ukraine", nameAr: "أوكرانيا" },
  { code: "+381", flag: E("RS"), country: "RS", name: "Serbia", nameAr: "صربيا" },
  { code: "+382", flag: E("ME"), country: "ME", name: "Montenegro", nameAr: "الجبل الأسود" },
  { code: "+383", flag: E("XK"), country: "XK", name: "Kosovo", nameAr: "كوسوفو" },
  { code: "+385", flag: E("HR"), country: "HR", name: "Croatia", nameAr: "كرواتيا" },
  { code: "+386", flag: E("SI"), country: "SI", name: "Slovenia", nameAr: "سلوفينيا" },
  {
    code: "+387",
    flag: E("BA"),
    country: "BA",
    name: "Bosnia and Herzegovina",
    nameAr: "البوسنة والهرسك",
  },
  {
    code: "+389",
    flag: E("MK"),
    country: "MK",
    name: "North Macedonia",
    nameAr: "مقدونيا الشمالية",
  },
  { code: "+39", flag: E("IT"), country: "IT", name: "Italy", nameAr: "إيطاليا" },
  { code: "+40", flag: E("RO"), country: "RO", name: "Romania", nameAr: "رومانيا" },
  { code: "+41", flag: E("CH"), country: "CH", name: "Switzerland", nameAr: "سويسرا" },
  { code: "+420", flag: E("CZ"), country: "CZ", name: "Czech Republic", nameAr: "التشيك" },
  { code: "+421", flag: E("SK"), country: "SK", name: "Slovakia", nameAr: "سلوفاكيا" },
  { code: "+423", flag: E("LI"), country: "LI", name: "Liechtenstein", nameAr: "ليختنشتاين" },
  { code: "+43", flag: E("AT"), country: "AT", name: "Austria", nameAr: "النمسا" },
  { code: "+44", flag: E("GB"), country: "GB", name: "United Kingdom", nameAr: "المملكة المتحدة" },
  { code: "+45", flag: E("DK"), country: "DK", name: "Denmark", nameAr: "الدنمارك" },
  { code: "+46", flag: E("SE"), country: "SE", name: "Sweden", nameAr: "السويد" },
  { code: "+47", flag: E("NO"), country: "NO", name: "Norway", nameAr: "النرويج" },
  { code: "+48", flag: E("PL"), country: "PL", name: "Poland", nameAr: "بولندا" },
  { code: "+49", flag: E("DE"), country: "DE", name: "Germany", nameAr: "ألمانيا" },

  // Zone 5 — Americas and the Caribbean.
  { code: "+500", flag: E("FK"), country: "FK", name: "Falkland Islands", nameAr: "جزر فوكلاند" },
  { code: "+501", flag: E("BZ"), country: "BZ", name: "Belize", nameAr: "بليز" },
  { code: "+502", flag: E("GT"), country: "GT", name: "Guatemala", nameAr: "غواتيمالا" },
  { code: "+503", flag: E("SV"), country: "SV", name: "El Salvador", nameAr: "السلفادور" },
  { code: "+504", flag: E("HN"), country: "HN", name: "Honduras", nameAr: "هندوراس" },
  { code: "+505", flag: E("NI"), country: "NI", name: "Nicaragua", nameAr: "نيكاراغوا" },
  { code: "+506", flag: E("CR"), country: "CR", name: "Costa Rica", nameAr: "كوستاريكا" },
  { code: "+507", flag: E("PA"), country: "PA", name: "Panama", nameAr: "بنما" },
  {
    code: "+508",
    flag: E("PM"),
    country: "PM",
    name: "Saint Pierre and Miquelon",
    nameAr: "سان بيير وميكلون",
  },
  { code: "+509", flag: E("HT"), country: "HT", name: "Haiti", nameAr: "هايتي" },
  { code: "+51", flag: E("PE"), country: "PE", name: "Peru", nameAr: "بيرو" },
  { code: "+52", flag: E("MX"), country: "MX", name: "Mexico", nameAr: "المكسيك" },
  { code: "+53", flag: E("CU"), country: "CU", name: "Cuba", nameAr: "كوبا" },
  { code: "+54", flag: E("AR"), country: "AR", name: "Argentina", nameAr: "الأرجنتين" },
  { code: "+55", flag: E("BR"), country: "BR", name: "Brazil", nameAr: "البرازيل" },
  { code: "+56", flag: E("CL"), country: "CL", name: "Chile", nameAr: "تشيلي" },
  { code: "+57", flag: E("CO"), country: "CO", name: "Colombia", nameAr: "كولومبيا" },
  { code: "+58", flag: E("VE"), country: "VE", name: "Venezuela", nameAr: "فنزويلا" },
  { code: "+590", flag: E("GP"), country: "GP", name: "Guadeloupe", nameAr: "غوادلوب" },
  { code: "+591", flag: E("BO"), country: "BO", name: "Bolivia", nameAr: "بوليفيا" },
  { code: "+592", flag: E("GY"), country: "GY", name: "Guyana", nameAr: "غيانا" },
  { code: "+593", flag: E("EC"), country: "EC", name: "Ecuador", nameAr: "الإكوادور" },
  { code: "+594", flag: E("GF"), country: "GF", name: "French Guiana", nameAr: "غويانا الفرنسية" },
  { code: "+595", flag: E("PY"), country: "PY", name: "Paraguay", nameAr: "باراغواي" },
  { code: "+596", flag: E("MQ"), country: "MQ", name: "Martinique", nameAr: "مارتينيك" },
  { code: "+597", flag: E("SR"), country: "SR", name: "Suriname", nameAr: "سورينام" },
  { code: "+598", flag: E("UY"), country: "UY", name: "Uruguay", nameAr: "أوروغواي" },
  { code: "+599", flag: E("CW"), country: "CW", name: "Curaçao", nameAr: "كوراساو" },

  // Zone 6 — Asia-Pacific and Oceania.
  { code: "+60", flag: E("MY"), country: "MY", name: "Malaysia", nameAr: "ماليزيا" },
  { code: "+61", flag: E("AU"), country: "AU", name: "Australia", nameAr: "أستراليا" },
  { code: "+62", flag: E("ID"), country: "ID", name: "Indonesia", nameAr: "إندونيسيا" },
  { code: "+63", flag: E("PH"), country: "PH", name: "Philippines", nameAr: "الفلبين" },
  { code: "+64", flag: E("NZ"), country: "NZ", name: "New Zealand", nameAr: "نيوزيلندا" },
  { code: "+65", flag: E("SG"), country: "SG", name: "Singapore", nameAr: "سنغافورة" },
  { code: "+66", flag: E("TH"), country: "TH", name: "Thailand", nameAr: "تايلاند" },
  { code: "+670", flag: E("TL"), country: "TL", name: "Timor-Leste", nameAr: "تيمور الشرقية" },
  { code: "+673", flag: E("BN"), country: "BN", name: "Brunei", nameAr: "بروناي" },
  { code: "+674", flag: E("NR"), country: "NR", name: "Nauru", nameAr: "ناورو" },
  {
    code: "+675",
    flag: E("PG"),
    country: "PG",
    name: "Papua New Guinea",
    nameAr: "بابوا غينيا الجديدة",
  },
  { code: "+676", flag: E("TO"), country: "TO", name: "Tonga", nameAr: "تونغا" },
  { code: "+677", flag: E("SB"), country: "SB", name: "Solomon Islands", nameAr: "جزر سليمان" },
  { code: "+678", flag: E("VU"), country: "VU", name: "Vanuatu", nameAr: "فانواتو" },
  { code: "+679", flag: E("FJ"), country: "FJ", name: "Fiji", nameAr: "فيجي" },
  { code: "+680", flag: E("PW"), country: "PW", name: "Palau", nameAr: "بالاو" },
  {
    code: "+681",
    flag: E("WF"),
    country: "WF",
    name: "Wallis and Futuna",
    nameAr: "واليس وفوتونا",
  },
  { code: "+682", flag: E("CK"), country: "CK", name: "Cook Islands", nameAr: "جزر كوك" },
  { code: "+683", flag: E("NU"), country: "NU", name: "Niue", nameAr: "نييوي" },
  { code: "+685", flag: E("WS"), country: "WS", name: "Samoa", nameAr: "ساموا" },
  { code: "+686", flag: E("KI"), country: "KI", name: "Kiribati", nameAr: "كيريباتي" },
  {
    code: "+687",
    flag: E("NC"),
    country: "NC",
    name: "New Caledonia",
    nameAr: "كاليدونيا الجديدة",
  },
  { code: "+688", flag: E("TV"), country: "TV", name: "Tuvalu", nameAr: "توفالو" },
  {
    code: "+689",
    flag: E("PF"),
    country: "PF",
    name: "French Polynesia",
    nameAr: "بولينيزيا الفرنسية",
  },
  { code: "+690", flag: E("TK"), country: "TK", name: "Tokelau", nameAr: "توكيلاو" },
  { code: "+691", flag: E("FM"), country: "FM", name: "Micronesia", nameAr: "ميكرونيزيا" },
  { code: "+692", flag: E("MH"), country: "MH", name: "Marshall Islands", nameAr: "جزر مارشال" },

  // Zone 7.
  { code: "+7", flag: E("RU"), country: "RU", name: "Russia", nameAr: "روسيا" },

  // Zone 8 — East Asia.
  { code: "+81", flag: E("JP"), country: "JP", name: "Japan", nameAr: "اليابان" },
  { code: "+82", flag: E("KR"), country: "KR", name: "South Korea", nameAr: "كوريا الجنوبية" },
  { code: "+84", flag: E("VN"), country: "VN", name: "Vietnam", nameAr: "فيتنام" },
  { code: "+850", flag: E("KP"), country: "KP", name: "North Korea", nameAr: "كوريا الشمالية" },
  { code: "+852", flag: E("HK"), country: "HK", name: "Hong Kong", nameAr: "هونغ كونغ" },
  { code: "+853", flag: E("MO"), country: "MO", name: "Macau", nameAr: "ماكاو" },
  { code: "+855", flag: E("KH"), country: "KH", name: "Cambodia", nameAr: "كمبوديا" },
  { code: "+856", flag: E("LA"), country: "LA", name: "Laos", nameAr: "لاوس" },
  { code: "+86", flag: E("CN"), country: "CN", name: "China", nameAr: "الصين" },
  { code: "+880", flag: E("BD"), country: "BD", name: "Bangladesh", nameAr: "بنغلاديش" },
  { code: "+886", flag: E("TW"), country: "TW", name: "Taiwan", nameAr: "تايوان" },

  // Zone 9 — South and West Asia.
  { code: "+90", flag: E("TR"), country: "TR", name: "Turkey", nameAr: "تركيا" },
  { code: "+91", flag: E("IN"), country: "IN", name: "India", nameAr: "الهند" },
  { code: "+92", flag: E("PK"), country: "PK", name: "Pakistan", nameAr: "باكستان" },
  { code: "+93", flag: E("AF"), country: "AF", name: "Afghanistan", nameAr: "أفغانستان" },
  { code: "+94", flag: E("LK"), country: "LK", name: "Sri Lanka", nameAr: "سريلانكا" },
  { code: "+95", flag: E("MM"), country: "MM", name: "Myanmar", nameAr: "ميانمار" },
  { code: "+98", flag: E("IR"), country: "IR", name: "Iran", nameAr: "إيران" },
  { code: "+960", flag: E("MV"), country: "MV", name: "Maldives", nameAr: "جزر المالديف" },
  { code: "+961", flag: E("LB"), country: "LB", name: "Lebanon", nameAr: "لبنان" },
  { code: "+962", flag: E("JO"), country: "JO", name: "Jordan", nameAr: "الأردن" },
  { code: "+963", flag: E("SY"), country: "SY", name: "Syria", nameAr: "سوريا" },
  { code: "+964", flag: E("IQ"), country: "IQ", name: "Iraq", nameAr: "العراق" },
  { code: "+967", flag: E("YE"), country: "YE", name: "Yemen", nameAr: "اليمن" },
  { code: "+970", flag: E("PS"), country: "PS", name: "Palestine", nameAr: "فلسطين" },
  { code: "+972", flag: E("IL"), country: "IL", name: "Israel", nameAr: "إسرائيل" },
  { code: "+975", flag: E("BT"), country: "BT", name: "Bhutan", nameAr: "بوتان" },
  { code: "+976", flag: E("MN"), country: "MN", name: "Mongolia", nameAr: "منغوليا" },
  { code: "+977", flag: E("NP"), country: "NP", name: "Nepal", nameAr: "نيبال" },
  { code: "+992", flag: E("TJ"), country: "TJ", name: "Tajikistan", nameAr: "طاجيكستان" },
  { code: "+993", flag: E("TM"), country: "TM", name: "Turkmenistan", nameAr: "تركمانستان" },
  { code: "+994", flag: E("AZ"), country: "AZ", name: "Azerbaijan", nameAr: "أذربيجان" },
  { code: "+995", flag: E("GE"), country: "GE", name: "Georgia", nameAr: "جورجيا" },
  { code: "+996", flag: E("KG"), country: "KG", name: "Kyrgyzstan", nameAr: "قيرغيزستان" },
  { code: "+998", flag: E("UZ"), country: "UZ", name: "Uzbekistan", nameAr: "أوزبكستان" },
];

/** Country-code digits without the "+", longest first for prefix matching. */
export const COUNTRY_CODE_DIGITS = COUNTRY_CODES.map((c) => c.code.slice(1)).sort(
  (a, b) => b.length - a.length,
);
