export interface CountryCode {
  code: string;
  flag: string;
  country: string;
}

/** Renders an ISO-2 country code as its flag emoji (e.g. "SA" → "🇸🇦"). */
function flagFor(country: string): string {
  return country
    .toUpperCase()
    .replace(/[A-Z]/g, (char) => String.fromCodePoint(127397 + char.charCodeAt(0)));
}

const E = flagFor;

/** Callable dialing codes offered in phone entry forms. */
export const COUNTRY_CODES: CountryCode[] = [
  // Gulf / primary market (kept on top for quick access).
  { code: "+966", flag: E("SA"), country: "SA" },
  { code: "+965", flag: E("KW"), country: "KW" },
  { code: "+971", flag: E("AE"), country: "AE" },
  { code: "+974", flag: E("QA"), country: "QA" },
  { code: "+973", flag: E("BH"), country: "BH" },
  { code: "+968", flag: E("OM"), country: "OM" },
  { code: "+20", flag: E("EG"), country: "EG" },
  { code: "+1", flag: E("US"), country: "US" },

  // Zone 2 — Africa.
  { code: "+211", flag: E("SS"), country: "SS" },
  { code: "+212", flag: E("MA"), country: "MA" },
  { code: "+213", flag: E("DZ"), country: "DZ" },
  { code: "+216", flag: E("TN"), country: "TN" },
  { code: "+218", flag: E("LY"), country: "LY" },
  { code: "+220", flag: E("GM"), country: "GM" },
  { code: "+221", flag: E("SN"), country: "SN" },
  { code: "+222", flag: E("MR"), country: "MR" },
  { code: "+223", flag: E("ML"), country: "ML" },
  { code: "+224", flag: E("GN"), country: "GN" },
  { code: "+225", flag: E("CI"), country: "CI" },
  { code: "+226", flag: E("BF"), country: "BF" },
  { code: "+227", flag: E("NE"), country: "NE" },
  { code: "+228", flag: E("TG"), country: "TG" },
  { code: "+229", flag: E("BJ"), country: "BJ" },
  { code: "+230", flag: E("MU"), country: "MU" },
  { code: "+231", flag: E("LR"), country: "LR" },
  { code: "+232", flag: E("SL"), country: "SL" },
  { code: "+233", flag: E("GH"), country: "GH" },
  { code: "+234", flag: E("NG"), country: "NG" },
  { code: "+235", flag: E("TD"), country: "TD" },
  { code: "+236", flag: E("CF"), country: "CF" },
  { code: "+237", flag: E("CM"), country: "CM" },
  { code: "+238", flag: E("CV"), country: "CV" },
  { code: "+239", flag: E("ST"), country: "ST" },
  { code: "+240", flag: E("GQ"), country: "GQ" },
  { code: "+241", flag: E("GA"), country: "GA" },
  { code: "+242", flag: E("CG"), country: "CG" },
  { code: "+243", flag: E("CD"), country: "CD" },
  { code: "+244", flag: E("AO"), country: "AO" },
  { code: "+245", flag: E("GW"), country: "GW" },
  { code: "+246", flag: E("IO"), country: "IO" },
  { code: "+248", flag: E("SC"), country: "SC" },
  { code: "+249", flag: E("SD"), country: "SD" },
  { code: "+250", flag: E("RW"), country: "RW" },
  { code: "+251", flag: E("ET"), country: "ET" },
  { code: "+252", flag: E("SO"), country: "SO" },
  { code: "+253", flag: E("DJ"), country: "DJ" },
  { code: "+254", flag: E("KE"), country: "KE" },
  { code: "+255", flag: E("TZ"), country: "TZ" },
  { code: "+256", flag: E("UG"), country: "UG" },
  { code: "+257", flag: E("BI"), country: "BI" },
  { code: "+258", flag: E("MZ"), country: "MZ" },
  { code: "+260", flag: E("ZM"), country: "ZM" },
  { code: "+261", flag: E("MG"), country: "MG" },
  { code: "+262", flag: E("RE"), country: "RE" },
  { code: "+263", flag: E("ZW"), country: "ZW" },
  { code: "+264", flag: E("NA"), country: "NA" },
  { code: "+265", flag: E("MW"), country: "MW" },
  { code: "+266", flag: E("LS"), country: "LS" },
  { code: "+267", flag: E("BW"), country: "BW" },
  { code: "+268", flag: E("SZ"), country: "SZ" },
  { code: "+269", flag: E("KM"), country: "KM" },
  { code: "+27", flag: E("ZA"), country: "ZA" },
  { code: "+290", flag: E("SH"), country: "SH" },
  { code: "+291", flag: E("ER"), country: "ER" },
  { code: "+297", flag: E("AW"), country: "AW" },
  { code: "+298", flag: E("FO"), country: "FO" },
  { code: "+299", flag: E("GL"), country: "GL" },

  // Zone 3 — Europe.
  { code: "+30", flag: E("GR"), country: "GR" },
  { code: "+31", flag: E("NL"), country: "NL" },
  { code: "+32", flag: E("BE"), country: "BE" },
  { code: "+33", flag: E("FR"), country: "FR" },
  { code: "+34", flag: E("ES"), country: "ES" },
  { code: "+350", flag: E("GI"), country: "GI" },
  { code: "+351", flag: E("PT"), country: "PT" },
  { code: "+352", flag: E("LU"), country: "LU" },
  { code: "+353", flag: E("IE"), country: "IE" },
  { code: "+354", flag: E("IS"), country: "IS" },
  { code: "+355", flag: E("AL"), country: "AL" },
  { code: "+356", flag: E("MT"), country: "MT" },
  { code: "+357", flag: E("CY"), country: "CY" },
  { code: "+358", flag: E("FI"), country: "FI" },
  { code: "+359", flag: E("BG"), country: "BG" },
  { code: "+36", flag: E("HU"), country: "HU" },
  { code: "+370", flag: E("LT"), country: "LT" },
  { code: "+371", flag: E("LV"), country: "LV" },
  { code: "+372", flag: E("EE"), country: "EE" },
  { code: "+373", flag: E("MD"), country: "MD" },
  { code: "+374", flag: E("AM"), country: "AM" },
  { code: "+375", flag: E("BY"), country: "BY" },
  { code: "+376", flag: E("AD"), country: "AD" },
  { code: "+377", flag: E("MC"), country: "MC" },
  { code: "+378", flag: E("SM"), country: "SM" },
  { code: "+380", flag: E("UA"), country: "UA" },
  { code: "+381", flag: E("RS"), country: "RS" },
  { code: "+382", flag: E("ME"), country: "ME" },
  { code: "+383", flag: E("XK"), country: "XK" },
  { code: "+385", flag: E("HR"), country: "HR" },
  { code: "+386", flag: E("SI"), country: "SI" },
  { code: "+387", flag: E("BA"), country: "BA" },
  { code: "+389", flag: E("MK"), country: "MK" },
  { code: "+39", flag: E("IT"), country: "IT" },
  { code: "+40", flag: E("RO"), country: "RO" },
  { code: "+41", flag: E("CH"), country: "CH" },
  { code: "+420", flag: E("CZ"), country: "CZ" },
  { code: "+421", flag: E("SK"), country: "SK" },
  { code: "+423", flag: E("LI"), country: "LI" },
  { code: "+43", flag: E("AT"), country: "AT" },
  { code: "+44", flag: E("GB"), country: "GB" },
  { code: "+45", flag: E("DK"), country: "DK" },
  { code: "+46", flag: E("SE"), country: "SE" },
  { code: "+47", flag: E("NO"), country: "NO" },
  { code: "+48", flag: E("PL"), country: "PL" },
  { code: "+49", flag: E("DE"), country: "DE" },

  // Zone 5 — Americas and the Caribbean.
  { code: "+500", flag: E("FK"), country: "FK" },
  { code: "+501", flag: E("BZ"), country: "BZ" },
  { code: "+502", flag: E("GT"), country: "GT" },
  { code: "+503", flag: E("SV"), country: "SV" },
  { code: "+504", flag: E("HN"), country: "HN" },
  { code: "+505", flag: E("NI"), country: "NI" },
  { code: "+506", flag: E("CR"), country: "CR" },
  { code: "+507", flag: E("PA"), country: "PA" },
  { code: "+508", flag: E("PM"), country: "PM" },
  { code: "+509", flag: E("HT"), country: "HT" },
  { code: "+51", flag: E("PE"), country: "PE" },
  { code: "+52", flag: E("MX"), country: "MX" },
  { code: "+53", flag: E("CU"), country: "CU" },
  { code: "+54", flag: E("AR"), country: "AR" },
  { code: "+55", flag: E("BR"), country: "BR" },
  { code: "+56", flag: E("CL"), country: "CL" },
  { code: "+57", flag: E("CO"), country: "CO" },
  { code: "+58", flag: E("VE"), country: "VE" },
  { code: "+590", flag: E("GP"), country: "GP" },
  { code: "+591", flag: E("BO"), country: "BO" },
  { code: "+592", flag: E("GY"), country: "GY" },
  { code: "+593", flag: E("EC"), country: "EC" },
  { code: "+594", flag: E("GF"), country: "GF" },
  { code: "+595", flag: E("PY"), country: "PY" },
  { code: "+596", flag: E("MQ"), country: "MQ" },
  { code: "+597", flag: E("SR"), country: "SR" },
  { code: "+598", flag: E("UY"), country: "UY" },
  { code: "+599", flag: E("CW"), country: "CW" },

  // Zone 6 — Asia-Pacific and Oceania.
  { code: "+60", flag: E("MY"), country: "MY" },
  { code: "+61", flag: E("AU"), country: "AU" },
  { code: "+62", flag: E("ID"), country: "ID" },
  { code: "+63", flag: E("PH"), country: "PH" },
  { code: "+64", flag: E("NZ"), country: "NZ" },
  { code: "+65", flag: E("SG"), country: "SG" },
  { code: "+66", flag: E("TH"), country: "TH" },
  { code: "+670", flag: E("TL"), country: "TL" },
  { code: "+673", flag: E("BN"), country: "BN" },
  { code: "+674", flag: E("NR"), country: "NR" },
  { code: "+675", flag: E("PG"), country: "PG" },
  { code: "+676", flag: E("TO"), country: "TO" },
  { code: "+677", flag: E("SB"), country: "SB" },
  { code: "+678", flag: E("VU"), country: "VU" },
  { code: "+679", flag: E("FJ"), country: "FJ" },
  { code: "+680", flag: E("PW"), country: "PW" },
  { code: "+681", flag: E("WF"), country: "WF" },
  { code: "+682", flag: E("CK"), country: "CK" },
  { code: "+683", flag: E("NU"), country: "NU" },
  { code: "+685", flag: E("WS"), country: "WS" },
  { code: "+686", flag: E("KI"), country: "KI" },
  { code: "+687", flag: E("NC"), country: "NC" },
  { code: "+688", flag: E("TV"), country: "TV" },
  { code: "+689", flag: E("PF"), country: "PF" },
  { code: "+690", flag: E("TK"), country: "TK" },
  { code: "+691", flag: E("FM"), country: "FM" },
  { code: "+692", flag: E("MH"), country: "MH" },

  // Zone 7.
  { code: "+7", flag: E("RU"), country: "RU" },

  // Zone 8 — East Asia.
  { code: "+81", flag: E("JP"), country: "JP" },
  { code: "+82", flag: E("KR"), country: "KR" },
  { code: "+84", flag: E("VN"), country: "VN" },
  { code: "+850", flag: E("KP"), country: "KP" },
  { code: "+852", flag: E("HK"), country: "HK" },
  { code: "+853", flag: E("MO"), country: "MO" },
  { code: "+855", flag: E("KH"), country: "KH" },
  { code: "+856", flag: E("LA"), country: "LA" },
  { code: "+86", flag: E("CN"), country: "CN" },
  { code: "+880", flag: E("BD"), country: "BD" },
  { code: "+886", flag: E("TW"), country: "TW" },

  // Zone 9 — South and West Asia.
  { code: "+90", flag: E("TR"), country: "TR" },
  { code: "+91", flag: E("IN"), country: "IN" },
  { code: "+92", flag: E("PK"), country: "PK" },
  { code: "+93", flag: E("AF"), country: "AF" },
  { code: "+94", flag: E("LK"), country: "LK" },
  { code: "+95", flag: E("MM"), country: "MM" },
  { code: "+98", flag: E("IR"), country: "IR" },
  { code: "+960", flag: E("MV"), country: "MV" },
  { code: "+961", flag: E("LB"), country: "LB" },
  { code: "+962", flag: E("JO"), country: "JO" },
  { code: "+963", flag: E("SY"), country: "SY" },
  { code: "+964", flag: E("IQ"), country: "IQ" },
  { code: "+967", flag: E("YE"), country: "YE" },
  { code: "+970", flag: E("PS"), country: "PS" },
  { code: "+975", flag: E("BT"), country: "BT" },
  { code: "+976", flag: E("MN"), country: "MN" },
  { code: "+977", flag: E("NP"), country: "NP" },
  { code: "+992", flag: E("TJ"), country: "TJ" },
  { code: "+993", flag: E("TM"), country: "TM" },
  { code: "+994", flag: E("AZ"), country: "AZ" },
  { code: "+995", flag: E("GE"), country: "GE" },
  { code: "+996", flag: E("KG"), country: "KG" },
  { code: "+998", flag: E("UZ"), country: "UZ" },
];

/** Country-code digits without the "+", longest first for prefix matching. */
export const COUNTRY_CODE_DIGITS = COUNTRY_CODES.map((c) => c.code.slice(1)).sort(
  (a, b) => b.length - a.length,
);