/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ListPropertyRouteImport } from './routes/list-property'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppTenantsRouteImport } from './routes/app.tenants'
import { Route as AppOwnersRouteImport } from './routes/app.owners'
import { Route as AppBuyersRouteImport } from './routes/app.buyers'
import { Route as AppAmenitiesRouteImport } from './routes/app.amenities'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ListPropertyRoute = ListPropertyRouteImport.update({
  id: '/list-property',
  path: '/list-property',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppTenantsRoute = AppTenantsRouteImport.update({
  id: '/tenants',
  path: '/tenants',
  getParentRoute: () => AppRoute,
} as any)
const AppOwnersRoute = AppOwnersRouteImport.update({
  id: '/owners',
  path: '/owners',
  getParentRoute: () => AppRoute,
} as any)
const AppBuyersRoute = AppBuyersRouteImport.update({
  id: '/buyers',
  path: '/buyers',
  getParentRoute: () => AppRoute,
} as any)
const AppAmenitiesRoute = AppAmenitiesRouteImport.update({
  id: '/amenities',
  path: '/amenities',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/list-property': typeof ListPropertyRoute
  '/login': typeof LoginRoute
  '/app/amenities': typeof AppAmenitiesRoute
  '/app/buyers': typeof AppBuyersRoute
  '/app/owners': typeof AppOwnersRoute
  '/app/tenants': typeof AppTenantsRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/list-property': typeof ListPropertyRoute
  '/login': typeof LoginRoute
  '/app/amenities': typeof AppAmenitiesRoute
  '/app/buyers': typeof AppBuyersRoute
  '/app/owners': typeof AppOwnersRoute
  '/app/tenants': typeof AppTenantsRoute
  '/app': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/list-property': typeof ListPropertyRoute
  '/login': typeof LoginRoute
  '/app/amenities': typeof AppAmenitiesRoute
  '/app/buyers': typeof AppBuyersRoute
  '/app/owners': typeof AppOwnersRoute
  '/app/tenants': typeof AppTenantsRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/list-property'
    | '/login'
    | '/app/amenities'
    | '/app/buyers'
    | '/app/owners'
    | '/app/tenants'
    | '/app/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/list-property'
    | '/login'
    | '/app/amenities'
    | '/app/buyers'
    | '/app/owners'
    | '/app/tenants'
    | '/app'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/list-property'
    | '/login'
    | '/app/amenities'
    | '/app/buyers'
    | '/app/owners'
    | '/app/tenants'
    | '/app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  ListPropertyRoute: typeof ListPropertyRoute
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/list-property': {
      id: '/list-property'
      path: '/list-property'
      fullPath: '/list-property'
      preLoaderRoute: typeof ListPropertyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/tenants': {
      id: '/app/tenants'
      path: '/tenants'
      fullPath: '/app/tenants'
      preLoaderRoute: typeof AppTenantsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/owners': {
      id: '/app/owners'
      path: '/owners'
      fullPath: '/app/owners'
      preLoaderRoute: typeof AppOwnersRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/buyers': {
      id: '/app/buyers'
      path: '/buyers'
      fullPath: '/app/buyers'
      preLoaderRoute: typeof AppBuyersRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/amenities': {
      id: '/app/amenities'
      path: '/amenities'
      fullPath: '/app/amenities'
      preLoaderRoute: typeof AppAmenitiesRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAmenitiesRoute: typeof AppAmenitiesRoute
  AppBuyersRoute: typeof AppBuyersRoute
  AppOwnersRoute: typeof AppOwnersRoute
  AppTenantsRoute: typeof AppTenantsRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAmenitiesRoute: AppAmenitiesRoute,
  AppBuyersRoute: AppBuyersRoute,
  AppOwnersRoute: AppOwnersRoute,
  AppTenantsRoute: AppTenantsRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  ListPropertyRoute: ListPropertyRoute,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
